config/routes.rb
Rails.application.routes.draw do
  resources :sauces
  resources :breads
  resources :selfie_posts
  resources :orders
  resources :users
  resources :drinks
  resources :payments
  resources :employees
  resources :sandwiches
  resources :ingredients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bread.rb
class Bread < ApplicationRecord
  has_and_belongs_to_many sandwiches
end

app/models/drink.rb
class Drink < ApplicationRecord
  has_and_belongs_to_many :orders
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_and_belongs_to_many :sandwiches
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :User
  has_and_belongs_to_many :drinks
  has_and_belongs_to_many :sandwiches
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/sandwich.rb
class Sandwich < ApplicationRecord
  has_and_belongs_to_many :ingredients
  has_and_belongs_to_many :sauces
  has_and_belongs_to_many :breads
  has_and_belongs_to_many :orders
end

app/models/sauce.rb
class Sauce < ApplicationRecord
  has_and_belongs_to_many :sandwiches
end

app/models/selfie_post.rb
class SelfiePost < ApplicationRecord
  belongs_to :User
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :selfie_posts
end

app/controllers/sandwiches_controller.rb
class SandwichesController < ApplicationController
  before_action :set_sandwich, only: [:show, :edit, :update, :destroy]

  # GET /sandwiches
  # GET /sandwiches.json
  def index
    @sandwiches = Sandwich.all
  end

  # GET /sandwiches/1
  # GET /sandwiches/1.json
  def show
  end

  # GET /sandwiches/new
  def new
    @sandwich = Sandwich.new
  end

  # GET /sandwiches/1/edit
  def edit
  end

  # POST /sandwiches
  # POST /sandwiches.json
  def create
    @sandwich = Sandwich.new(sandwich_params)

    respond_to do |format|
      if @sandwich.save
        format.html { redirect_to @sandwich, notice: 'Sandwich was successfully created.' }
        format.json { render :show, status: :created, location: @sandwich }
      else
        format.html { render :new }
        format.json { render json: @sandwich.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sandwiches/1
  # PATCH/PUT /sandwiches/1.json
  def update
    respond_to do |format|
      if @sandwich.update(sandwich_params)
        format.html { redirect_to @sandwich, notice: 'Sandwich was successfully updated.' }
        format.json { render :show, status: :ok, location: @sandwich }
      else
        format.html { render :edit }
        format.json { render json: @sandwich.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sandwiches/1
  # DELETE /sandwiches/1.json
  def destroy
    @sandwich.destroy
    respond_to do |format|
      format.html { redirect_to sandwiches_url, notice: 'Sandwich was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sandwich
      @sandwich = Sandwich.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sandwich_params
      params.require(:sandwich).permit(:bread_type, :sauce, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breads_helper.rb
module BreadsHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sandwiches_helper.rb
module SandwichesHelper
end

app/helpers/sauces_helper.rb
module SaucesHelper
end

app/helpers/selfie_posts_helper.rb
module SelfiePostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sandwiches/_form.html.erb
<%= form_for(sandwich) do |f| %>
  <% if sandwich.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sandwich.errors.count, "error") %> prohibited this sandwich from being saved:</h2>

      <ul>
      <% sandwich.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bread_type %>
    <%= f.text_field :bread_type %>
  </div>

  <div class="field">
    <%= f.label :sauce %>
    <%= f.text_field :sauce %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sandwiches/edit.html.erb
<h1>Editing Sandwich</h1>

<%= render 'form', sandwich: @sandwich %>

<%= link_to 'Show', @sandwich %> |
<%= link_to 'Back', sandwiches_path %>

app/views/sandwiches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sandwiches</h1>

<table>
  <thead>
    <tr>
      <th>Bread type</th>
      <th>Sauce</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sandwiches.each do |sandwich| %>
      <tr>
        <td><%= sandwich.bread_type %></td>
        <td><%= sandwich.sauce %></td>
        <td><%= sandwich.price %></td>
        <td><%= link_to 'Show', sandwich %></td>
        <td><%= link_to 'Edit', edit_sandwich_path(sandwich) %></td>
        <td><%= link_to 'Destroy', sandwich, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sandwich', new_sandwich_path %>

app/views/sandwiches/new.html.erb
<h1>New Sandwich</h1>

<%= render 'form', sandwich: @sandwich %>

<%= link_to 'Back', sandwiches_path %>

app/views/sandwiches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bread type:</strong>
  <%= @sandwich.bread_type %>
</p>

<p>
  <strong>Sauce:</strong>
  <%= @sandwich.sauce %>
</p>

<p>
  <strong>Price:</strong>
  <%= @sandwich.price %>
</p>

<%= link_to 'Edit', edit_sandwich_path(@sandwich) %> |
<%= link_to 'Back', sandwiches_path %>