config/routes.rb
Rails.application.routes.draw do
  resources :sauces
  resources :breads
  resources :selfie_posts
  resources :orders
  resources :users
  resources :drinks
  resources :payments
  resources :employees
  resources :sandwiches
  resources :ingredients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bread.rb
class Bread < ApplicationRecord
  has_and_belongs_to_many sandwiches
end

app/models/drink.rb
class Drink < ApplicationRecord
  has_and_belongs_to_many :orders
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_and_belongs_to_many :sandwiches
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :User
  has_and_belongs_to_many :drinks
  has_and_belongs_to_many :sandwiches
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/sandwich.rb
class Sandwich < ApplicationRecord
  has_and_belongs_to_many :ingredients
  has_and_belongs_to_many :sauces
  has_and_belongs_to_many :breads
  has_and_belongs_to_many :orders
end

app/models/sauce.rb
class Sauce < ApplicationRecord
  has_and_belongs_to_many :sandwiches
end

app/models/selfie_post.rb
class SelfiePost < ApplicationRecord
  belongs_to :User
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :selfie_posts
end

app/controllers/selfie_posts_controller.rb
class SelfiePostsController < ApplicationController
  before_action :set_selfie_post, only: [:show, :edit, :update, :destroy]

  # GET /selfie_posts
  # GET /selfie_posts.json
  def index
    @selfie_posts = SelfiePost.all
  end

  # GET /selfie_posts/1
  # GET /selfie_posts/1.json
  def show
  end

  # GET /selfie_posts/new
  def new
    @selfie_post = SelfiePost.new
  end

  # GET /selfie_posts/1/edit
  def edit
  end

  # POST /selfie_posts
  # POST /selfie_posts.json
  def create
    @selfie_post = SelfiePost.new(selfie_post_params)

    respond_to do |format|
      if @selfie_post.save
        format.html { redirect_to @selfie_post, notice: 'Selfie post was successfully created.' }
        format.json { render :show, status: :created, location: @selfie_post }
      else
        format.html { render :new }
        format.json { render json: @selfie_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /selfie_posts/1
  # PATCH/PUT /selfie_posts/1.json
  def update
    respond_to do |format|
      if @selfie_post.update(selfie_post_params)
        format.html { redirect_to @selfie_post, notice: 'Selfie post was successfully updated.' }
        format.json { render :show, status: :ok, location: @selfie_post }
      else
        format.html { render :edit }
        format.json { render json: @selfie_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selfie_posts/1
  # DELETE /selfie_posts/1.json
  def destroy
    @selfie_post.destroy
    respond_to do |format|
      format.html { redirect_to selfie_posts_url, notice: 'Selfie post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selfie_post
      @selfie_post = SelfiePost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selfie_post_params
      params.require(:selfie_post).permit(:description, :picture_url, :User_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breads_helper.rb
module BreadsHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sandwiches_helper.rb
module SandwichesHelper
end

app/helpers/sauces_helper.rb
module SaucesHelper
end

app/helpers/selfie_posts_helper.rb
module SelfiePostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/selfie_posts/_form.html.erb
<%= form_for(selfie_post) do |f| %>
  <% if selfie_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(selfie_post.errors.count, "error") %> prohibited this selfie_post from being saved:</h2>

      <ul>
      <% selfie_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :picture_url %>
    <%= f.text_field :picture_url %>
  </div>

  <div class="field">
    <%= f.label :User_id %>
    <%= f.text_field :User_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/selfie_posts/edit.html.erb
<h1>Editing Selfie Post</h1>

<%= render 'form', selfie_post: @selfie_post %>

<%= link_to 'Show', @selfie_post %> |
<%= link_to 'Back', selfie_posts_path %>

app/views/selfie_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Selfie Posts</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Picture url</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @selfie_posts.each do |selfie_post| %>
      <tr>
        <td><%= selfie_post.description %></td>
        <td><%= selfie_post.picture_url %></td>
        <td><%= selfie_post.User %></td>
        <td><%= link_to 'Show', selfie_post %></td>
        <td><%= link_to 'Edit', edit_selfie_post_path(selfie_post) %></td>
        <td><%= link_to 'Destroy', selfie_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Selfie Post', new_selfie_post_path %>

app/views/selfie_posts/new.html.erb
<h1>New Selfie Post</h1>

<%= render 'form', selfie_post: @selfie_post %>

<%= link_to 'Back', selfie_posts_path %>

app/views/selfie_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @selfie_post.description %>
</p>

<p>
  <strong>Picture url:</strong>
  <%= @selfie_post.picture_url %>
</p>

<p>
  <strong>User:</strong>
  <%= @selfie_post.User %>
</p>

<%= link_to 'Edit', edit_selfie_post_path(@selfie_post) %> |
<%= link_to 'Back', selfie_posts_path %>