config/routes.rb
Rails.application.routes.draw do
  resources :sauces
  resources :breads
  resources :selfie_posts
  resources :orders
  resources :users
  resources :drinks
  resources :payments
  resources :employees
  resources :sandwiches
  resources :ingredients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bread.rb
class Bread < ApplicationRecord
  has_and_belongs_to_many sandwiches
end

app/models/drink.rb
class Drink < ApplicationRecord
  has_and_belongs_to_many :orders
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_and_belongs_to_many :sandwiches
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :User
  has_and_belongs_to_many :drinks
  has_and_belongs_to_many :sandwiches
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/sandwich.rb
class Sandwich < ApplicationRecord
  has_and_belongs_to_many :ingredients
  has_and_belongs_to_many :sauces
  has_and_belongs_to_many :breads
  has_and_belongs_to_many :orders
end

app/models/sauce.rb
class Sauce < ApplicationRecord
  has_and_belongs_to_many :sandwiches
end

app/models/selfie_post.rb
class SelfiePost < ApplicationRecord
  belongs_to :User
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :selfie_posts
end

app/controllers/sauces_controller.rb
class SaucesController < ApplicationController
  before_action :set_sauce, only: [:show, :edit, :update, :destroy]

  # GET /sauces
  # GET /sauces.json
  def index
    @sauces = Sauce.all
  end

  # GET /sauces/1
  # GET /sauces/1.json
  def show
  end

  # GET /sauces/new
  def new
    @sauce = Sauce.new
  end

  # GET /sauces/1/edit
  def edit
  end

  # POST /sauces
  # POST /sauces.json
  def create
    @sauce = Sauce.new(sauce_params)

    respond_to do |format|
      if @sauce.save
        format.html { redirect_to @sauce, notice: 'Sauce was successfully created.' }
        format.json { render :show, status: :created, location: @sauce }
      else
        format.html { render :new }
        format.json { render json: @sauce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sauces/1
  # PATCH/PUT /sauces/1.json
  def update
    respond_to do |format|
      if @sauce.update(sauce_params)
        format.html { redirect_to @sauce, notice: 'Sauce was successfully updated.' }
        format.json { render :show, status: :ok, location: @sauce }
      else
        format.html { render :edit }
        format.json { render json: @sauce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sauces/1
  # DELETE /sauces/1.json
  def destroy
    @sauce.destroy
    respond_to do |format|
      format.html { redirect_to sauces_url, notice: 'Sauce was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sauce
      @sauce = Sauce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sauce_params
      params.require(:sauce).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breads_helper.rb
module BreadsHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/sandwiches_helper.rb
module SandwichesHelper
end

app/helpers/sauces_helper.rb
module SaucesHelper
end

app/helpers/selfie_posts_helper.rb
module SelfiePostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sauces/_form.html.erb
<%= form_for(sauce) do |f| %>
  <% if sauce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sauce.errors.count, "error") %> prohibited this sauce from being saved:</h2>

      <ul>
      <% sauce.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sauces/edit.html.erb
<h1>Editing Sauce</h1>

<%= render 'form', sauce: @sauce %>

<%= link_to 'Show', @sauce %> |
<%= link_to 'Back', sauces_path %>

app/views/sauces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sauces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sauces.each do |sauce| %>
      <tr>
        <td><%= sauce.name %></td>
        <td><%= sauce.price %></td>
        <td><%= link_to 'Show', sauce %></td>
        <td><%= link_to 'Edit', edit_sauce_path(sauce) %></td>
        <td><%= link_to 'Destroy', sauce, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sauce', new_sauce_path %>

app/views/sauces/new.html.erb
<h1>New Sauce</h1>

<%= render 'form', sauce: @sauce %>

<%= link_to 'Back', sauces_path %>

app/views/sauces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sauce.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @sauce.price %>
</p>

<%= link_to 'Edit', edit_sauce_path(@sauce) %> |
<%= link_to 'Back', sauces_path %>